name: FakeFullPlayer
main: com.gumball.fake.FakeFullPlayer
version: 1.1
api-version: 1.21
commands:
  fakespawn:
    description: Spawn a fake player at your location
    usage: /fakespawn <name>
  fakeremove:
    description: Remove a fake player by UUID or name
    usage: /fakeremove <uuid|name>
  fakeremoveall:
    description: Remove all fake players
    usage: /fakeremoveall
  fakechat:
    description: Make a fake player send a chat message
    usage: /fakechat <name> <message>
depend: [ProtocolLib]
